(function(){google.isOpera=false;google.isIE=false;google.isSafari=false;
google.xhr=function(){var a=null;try{a=new XMLHttpRequest}catch(d){}return a};
google.getComputedStyle=function(a,d,b){var c=b?"":0;var e=document.defaultView&&document.defaultView.getComputedStyle(a,"");c=e.getPropertyValue(d);c=b?c:parseInt(c,10);return c};google.getHeight=function(a){return google.getComputedStyle(a,"height")};google.getWidth=function(a){return google.getComputedStyle(a,"width")};google.getPageOffsetTop=function(a){return a.offsetTop+(a.offsetParent?google.getPageOffsetTop(a.offsetParent):0)};
google.getPageOffsetLeft=function(a){return a.offsetLeft+(a.offsetParent?google.getPageOffsetLeft(a.offsetParent):0)};google.getPageOffsetStart=function(a){return google.getPageOffsetLeft(a)};google.getColor=function(a){return google.getComputedStyle(a,"color",true)};google.rhs=function(){};var f,g=location;
google.nav=function(a,d){try{var b=location.protocol+"//"+location.host;if((new RegExp("^("+b+")?/url\\?.*&rct=j(&|$)")).test(a))if(d){google.r=1;d.location.replace(a)}else{if(!f){f=document.createElement("iframe");f.style.display="none";google.append(f)}google.r=1;f.src=a}else g.href=a}catch(c){g.href=a}};google.append=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)};google.bind=function(a,d,b){a.addEventListener(d,b,false);};window.google.unbind=function(a,d,b){a.removeEventListener(d,b,false);};})();
(function(){var c=window,f=Object,h=google,i="push",j="length",k="propertyIsEnumerable",l="prototype",m="call";
function n(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof f)&&f[l].toString[m](a)=="[object Array]"||typeof a[j]=="number"&&typeof a.splice!="undefined"&&typeof a[k]!="undefined"&&!a[k]("splice"))return"array";if(!(a instanceof f)&&(f[l].toString[m](a)=="[object Function]"||typeof a[m]!="undefined"&&typeof a[k]!="undefined"&&!a[k]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[m]=="undefined")return"object";return b}
function o(a){return(new p).serialize(a)}function p(){}p[l].serialize=function(a){var b=[];this.a(a,b);return b.join("")};p[l].a=function(a,b){switch(typeof a){case "string":this.b(a,b);break;case "number":this.d(a,b);break;case "boolean":b[i](a);break;case "undefined":b[i]("null");break;case "object":if(a==null){b[i]("null");break}if(n(a)=="array"){this.c(a,b);break}this.e(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var q={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},r=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;p[l].b=function(a,b){b[i]('"',a.replace(r,function(g){if(g in q)return q[g];var d=g.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return q[g]=e+d.toString(16)}),'"')};p[l].d=function(a,b){b[i](isFinite(a)&&!isNaN(a)?a:"null")};
p[l].c=function(a,b){var g=a[j];b[i]("[");for(var d="",e=0;e<g;e++){b[i](d);this.a(a[e],b);d=","}b[i]("]")};p[l].e=function(a,b){b[i]("{");var g="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b[i](g);this.b(d,b);b[i](":");this.a(e,b);g=","}}b[i]("}")};c.google.stringify=o;if(c.JSON&&c.JSON.stringify&&navigator.userAgent.indexOf("Chrome")==-1)c.google.stringify=c.JSON.stringify;h.History={};var s=[],t="/";h.History.client=function(a){s[i](a);return s[j]-1};var u,v;function w(){var a=u.value;v=a?eval("("+a+")"):{}}function x(a,b){w();v[t]||(v[t]={});v[t][a]=b;u.value=h.stringify(v)}function y(a,b){return function(){x(a,b)}}var z=[];function A(){for(var a=0,b;b=z[a++];)b();z=[]}h.History.save=function(a,b){u?x(a,b):z[i](y(a,b))};
h.History.initialize=function(a){t=a;v=null;if(u=document.getElementById("hcache")){w();for(a=0;a<s[j];++a)v&&v[t]&&v[t][a]&&s[a][m](null,v[t][a]);A()}};})();
(function(){var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":google.isIE?"":0}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.bind(window,"resize",google.rhs);google.rein.push(e);})();
(function(){var f=0,g=[];google.fx={};google.fx.linear=function(a){return a};google.fx.easeOut=function(a){return 1-Math.pow(1-a,3)};google.fx.easeInAndOut=function(a){return(3-2*a)*a*a};google.fx.animate=function(a,d,e){for(var c=0,b;b=d[c++];){b[5]=b[5]==null?"px":b[5];b[4]=b[4]||google.fx.linear;h(b[0],b[1],b[2]+b[5])}g.push({b:a,a:e,d:google.time(),c:d});f=f||window.setInterval(i,15)};function i(){for(var a=0,d;d=g[a++];)j(d)||g.splice(--a,1);if(!g.length){window.clearInterval(f);f=0}}
function j(a){var d=google.time()-a.d;if(d>=a.b){for(var e=0,c;c=a.c[e++];)h(c[0],c[1],c[3]+c[5]);a.a&&a.a();return 0}else{for(e=0;c=a.c[e++];){var b=c[2]+(c[3]-c[2])*c[4](d/a.b);if(c[5]=="px")b=Math.round(b);h(c[0],c[1],b+c[5])}return 1}}
function h(a){for(var d=1;d<arguments.length;d+=2){var e=arguments[d],c=arguments[d+1],b=a.style;if(b&&e in b)b[e]=c;else if(e in a)a[e]=c;}return a}
google.fx.wrap=function(a){var d=document.createElement("div");a.parentNode.replaceChild(d,a);d.appendChild(a);return d};google.fx.unwrap=function(a){a.parentNode.parentNode.replaceChild(a,a.parentNode)};google.dstr.push(function(){window.clearInterval(f);f=0;g=[]});})();
(function(){var f=true,j=null,k=false,l=window.google.ac={},aa=k,m,ba,ca,da,ea,fa,ga,ha,n,o,p,ia,q="",ja=j,r=j,u=j,v=-1,w,x,z,A,B,ka,C,E,F,la,na,oa,H,pa,qa={},ra,I=0,K=0,sa=k,L=j,M=0,ta,ua;var N;
var S;function ya(a){return(a=a&&a.match(/\D+$/))?a[0]:j}var za="hp",Aa="serp",Ba="img",Ca={0:za,1:Aa,2:Ba},T;
function Da(){if(F){Ea();U();F.value=la.value=na.value=H.value=oa.value="";window.clearTimeout(ja);q=ua=ra="";ja=r=u=j;v=-1;T=I=K=M=0;qa={};N=0;}}function Fa(a,b){T=0;if(a=="i")T=2;else if(b&&b!="")T=1}
function Ga(a,b,c,d,e,h){Fa(c,d);Ha();h&&Ia(h);Ja();w=a;x=b;p=ia=o=x.value;if(!b.init){ta=document.getElementsByTagName("head")[0];google.bind(w,"submit",Ka);x.setAttribute("autocomplete","off");google.bind(x,"blur",U);google.bind(x,"keypress",La);
google.bind(x,"keyup",Ma);F=V("aq","f");la=V("aqi","");na=V("aql","");H=V("oq",p);oa=V("gs_rfai","");C=B=document.createElement("table");B.cellSpacing=B.cellPadding="0";E=ka=B.style;B.className="gac_m";if(n){C=z=document.createElement("div");z.className="gac_od";E=z.style;(document.getElementById("xjsc")||document.body).appendChild(z);if(T==1){a=document.createElement("div");a.className="gac_wd";
z.appendChild(a)}A=document.createElement("div");A.cellSpacing=z.cellPadding="0";A.className="gac_id";z.appendChild(A);A.appendChild(B)}else w.appendChild(B);b.init=f}U();Na();if(!aa){Oa();aa=f}b=Ca[T];b="&client="+b;
c=c?"&ds="+c:"";a=e?"&tok="+encodeURIComponent(e):"";d=["?hl=",google.kHL,b,Pa(),c,(d?"&pq="+encodeURIComponent(d):""),a].join("");ra="/complete/search"+d;ua="/complete/deleteitems"+d;N=Qa(x);
Sa();e=ga||e&&e.length;ha=["http",e?"s":"","://"].join("");(new Image).src=ha+"clients1.google.com/generate_204";}
function Oa(){function a(d,e){b.push(d,"{",e,"}")}var b=[];if(n){var c="background:white;margin:0;z-index:99;";a(".gac_od",c+"border-top:0;border-left:0;border-right:1px solid #e7e7e7;border-bottom:1px solid #e7e7e7;padding:0!important;position:absolute");a(".gac_id",c+"border-top:1px solid #a2bff0;border-left:1px solid #a2bff0;border-right:1px solid #558be3;border-bottom:1px solid #558be3;display:block;position:relative");a(".gac_m",c+"border:0;cursor:default;display:block;font-size:17px;line-height:117%;padding:0;position:relative");
a(".gac_wd","background:#999;height:1px;position:absolute;right:-1px;top:0;width:1px;z-index:100")}else a(".gac_m","background:white;border:1px solid #666;cursor:default;font-size:17px;line-height:117%;margin:0;position:absolute;z-index:99");a(".gac_m td","line-height:22px");a(".gac_n","padding-top:1px;padding-bottom:1px");a(".gac_b td.gac_c","background:#d5e2ff");a(".gac_b","background:#d5e2ff");
a(".gac_a td.gac_f","background:#fff8dd");a(".gac_p","padding:1px 4px 2px 3px");a(".gac_u","padding:0 0 1px 0;line-height:117%;text-align:left");a(".gac_t","width:100%;text-align:left;font-size:17px");a(".gac_bt","width:"+(x.offsetWidth-2)+"px;text-align:center;padding:8px 0 7px");a(".gac_sb","font-size:15px;height:28px;margin:0.2em");a(".gac_z","white-space:nowrap;color:#c00");a(".gac_s","height:3px;font-size:1px");c=n?7:3;c="white-space:nowrap;overflow:hidden;text-align:left;padding-left:"+c+"px;padding-right:3px";a(".gac_c",c);a(".gac_e","text-align:right;padding:0 3px");a(".gac_d","font-size:11px");a(".fl,a:link.fl,a:visited.fl","color:#77c");
a(".gac_h","color:green");a(".gac_j","display:block");a(".gac_l","line-height:18px");a(".gac_x","display:block;line-height:16px");a(".gac_y","font-size:13px");a(".gac_i","color:#666");a(".gac_w img","width:40px;height:40px");a(".gac_w","width:1px");a(".gac_r","color:red");a(".gac_v","padding-bottom:5px");c=document.createElement("style");c.setAttribute("type","text/css");ta.appendChild(c);b=b.join("");c.appendChild(document.createTextNode(b));}
function Na(){if(C){var a=Ta(x);E.left=a.F+"px";a=a.H+x.offsetHeight-1;n&&T==1&&a++;E.top=a+"px";a=x.offsetWidth+"px";if(n)E.minWidth=a;else E.width=a;if(r)if(a=W(0))a.firstChild.style.width=x.offsetWidth-12+"px";}}function Ta(a){for(var b=0,c=0;a;){b+=a.offsetTop;c+=a.offsetLeft;a=a.offsetParent}return{H:b,F:c}}
function V(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return w.appendChild(c)}function La(a){var b=a.keyCode;if(b==27&&Ua()){U();X(p);a.cancelBubble=f;return a.returnValue=k}if(b==13){Va(k);a.cancelBubble=f;return a.returnValue=k}if(b==38||b==40){K++;K%3==1&&Ra(b);return k}}
function Va(a){if(!a&&pa){w.removeChild(pa);pa=j}if(u&&v!=-1&&sa&&!(a&&u.D))u.onclick(j);else if(x.value=="")U();else{if(a)pa=V("btnI","1");Wa()}}function Wa(){Ka();w.onsubmit&&w.onsubmit()==k||w.submit()}function Ma(a){a=a.keyCode;if(!K)Ra(a);K=0;}
function Ra(a){if(x.value!=o){p=x.value;N=Qa(x);H.value=p}if(a==40||a==38){Xa(a==40);sa=Ua()}Na();if(q!=p&&!L)L=window.setTimeout(U,500);o=x.value}
function Ya(){sa=k;if(!M){if(u)u.className="gac_a";u=this;for(var a=0,b;b=W(a);a++)b==u&&(v=a);u.className="gac_b"}}function Za(a,b){return function(){$a(ab(a),b);return k}}function ab(a){return[a,"&aq=",u.t,"&oq=",H.value,Z("aqi",la),Z("aql",na),Z("gs_rfai",oa)].join("")}
function Z(a,b){if(b&&b.value.length&&a.length)return["&",a,"=",b.value].join("");return""}function $a(a,b){var c=window.frames.wgjf;if(c&&!b){google.r=1;c.location.replace(a)}else window.location=a}
function bb(){X(this.j);Wa();}
function Xa(a){if(!(p!=q||!r||!r.length))if(Ua()){if(u)u.className="gac_a";for(var b=r.length,c=(v+1+(a?1:b))%(b+1)-1;c!=-1&&W(c).z;)c=(c+1+(a?1:b))%(b+1)-1;v=c;if(v==-1)cb();else{u=W(c);u.className="gac_b";X(u.j);F.value=u.t}}else db()}function cb(){x.focus();X(p);u=j;F.value="f"}function U(){if(L){window.clearTimeout(L);L=j}E&&(E.visibility="hidden");}
function db(){E&&(E.visibility="visible");Na();M=1}function Ua(){return!!E&&E.visibility=="visible"}function Ea(){if(B){B.innerHTML="";}}
function eb(a,b,c){a.onclick=b?Za(b,c):bb;a.D=!b;a.onmousedown=fb;a.onmouseover=Ya;a.onmousemove=function(){if(M){M=0;Ya.call(this)}}}function gb(a,b){hb(a);a=0;for(var c;c=W(a++);)if(c.t==b){ib(ua,"delq",c.j,jb);break}return k}function jb(a){for(var b=0,c;c=W(b++);)if(ya(c.t)=="p"&&c.j==a[0]){c.z=1;c.onclick=c.onmouseover=j;if(c==u){c.className="gac_a";v=-1;cb()}c.A.className="gac_c gac_i fl";c.A.innerHTML="This search was removed from your \x3ca href\x3d\x22/history\x22\x3eWeb History\x3c/a\x3e"}}
function kb(a){function b(ma,Y){Y=Y?ya(Y[2]):j;ma=ma+(Y?"-"+Y:"");if(ma!=e){if(h)d+=e+h;h=0;e=ma}h++}var c=a[0];I>0&&I--;if(!(!B||c!=p)){if(L){window.clearTimeout(L);L=j}q=a[0];Ea();var d="",e,h=0;c=a[1];for(var g=c.length-1,i=0,s,t,G,y,J,D;i<=g;i++)if(D=c[i])if(y=qa[D[1]]){y.B&&y.B(i,g)&&lb();s=D[2];t=D[3];G=y.g?y.g(D,t):j;J=B.insertRow(-1);eb(J,G,y.C);J.t=s;J.className="gac_a";G=J.A=document.createElement("td");G.className=
"gac_c";y.e(G,s,D,t);s=y.w;J.j=s?s(D,t,q):D[0];J.appendChild(G);b(y.b,D);i<g&&y.G&&lb()}na.value=a[3]||"";oa.value=a[4]||"";if((r=B.rows)&&r.length>0){T==0&&nb();db()}else U();b("");la.value=d;v=-1}}
function W(a){b=r.item(a);return b}function ob(a){var b=a?"I\x26#39;m Feeling Lucky":"Google Search",c="gac_sb",d="",e="";if(n){c="lsb";d="<span class=ds><span class=lsbb>";e="</span></span>"}return[d,'<input type=button value="',b,'" class=',c,' onclick="google.ac.rd(',a,')">',e].join("")}
function nb(){var a=B.insertRow(-1);a.z=1;a.onmousedown=fb;a=a.insertCell(0);a.innerHTML=["<div class=gac_bt>",ob(k),ob(f),"</div>"].join("")}function pb(a){return a.replace(/<\/?[b|em]>/gi,"")}function $(a,b){return['href="',a,'" onmousedown="google.ac.r(event, this, \'',b,'\')" onclick="return google.ac.c(event)"'].join("")}
function qb(a,b,c){m=k;if(a.which)m=a.which==2;else if(a.button)m=a.button==4;b.href=ab(c)}function rb(a){if(m){hb(a);return f}return k}
function hb(a){a.cancelBubble=a.cancel=a.returnValue=f}
function lb(){var a=B.insertRow(-1);a.z=1;a.onmousedown=fb;a.insertCell(0).className="gac_s"}function Ka(){U();if(r&&W(v)&&H.value!=x.value)F.value=W(v).t;else{H.value="";F.value="f";if(I>=10)F.value="o"}}function Sa(){if(p&&ia!=p){I++;ib(ra,"q",p,kb);x.focus()}ia=p;for(var a=100,b=1;b<=(I-2)/2;b++)a*=2;a+=50;ja=window.setTimeout(Sa,a)}
function ib(a,b,c,d){S&&ta.removeChild(S);S=document.createElement("script");S.src=[ha,"clients1.google.com",a,"&",b,"=",encodeURIComponent(c),"&cp="+N].join("");ta.appendChild(S);}function X(a){if(x)x.value=o=a}function mb(a,b){a.appendChild(document.createTextNode(b))}
function fb(a){return k}
function Qa(a){var b=0,c=0;if(vb(a)){b=a.selectionStart;c=a.selectionEnd}return b&&c&&b==c?b:0}function vb(a){try{return typeof a.selectionStart=="number"}catch(b){return k}}
function wb(a){var b=[];a=a.replace(/\s+<\/b>/g,"</b> ");var c=p.replace(/^\s+/,"").replace(/\s{2,}/g," ").split(" "),d=a.split(" ");a=pb(a).split(" ");for(var e={q:"",v:0,k:0,m:0},h,g,i;e.m<a.length;++e.m){i=d[e.m];if(e.k==c.length)b.push(i," ");else{h=c[e.k];g=a[e.m];if(h==g){++e.k;b.push(i," ")}else{xb(h,g,c,a,e,f,d);h=e.k==c.length;b.push(yb(e.v,h,i,e.q,"<b><i>","</i></b>"))}}}return zb(b.join(""))}
function yb(a,b,c,d,e,h){d=d&&d.length?zb(d):c;if(a==1&&b)return d+" ";return[e,d,h," "].join("")}function xb(a,b,c,d,e,h,g){e.k=Ab(b,c,e.k,e,!h);if(e.v==0){e.m=Ab(a,d,e.m,e,h,g);++e.k;e.v>0&&--e.m}}function Ab(a,b,c,d,e,h){d.q=[];for(var g=d.v=0,i=a.length,s=b.length,t=b[c];g<i&&Bb(a.substr(g),t);){if(e)d.q.push(h?h[c]:t," ");++d.v;g+=t.length;if(++c==s)break;t=b[c]}d.q=d.q.join("");return c}function Bb(a,b){return a.substr(0,b.length)==b}
function zb(a){var b=a.length-1;return a.substr(b)==" "?a.substring(0,b):a}function Ha(){ba=f;ca=k;da=f;ea=k;fa=f;n=ga=k}function Ia(a){if("a"in a)ba=a.a;if("l"in a)ca=a.l;if("n"in a)da=a.n;if("o"in a)ea=a.o;if(T==2)fa=k;else if("p"in a)fa=a.p;if("s"in a)ga=a.s;if("sw"in a)n=a.sw}function Ja(){var a=[Cb];ba&&a.push(Db);ca&&a.push(Eb);da&&a.push(Fb);ea&&a.push(Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb);Qb(a)}function Qb(a){for(var b=0,c;c=a[b++];)qa[c.f]=c}
var Db={f:8,b:"a",G:f,w:function(a,b,c){return c},g:function(a,b){return b[1]+Pa()},B:function(a,b){return a==b},e:function(a,b,c,d){b=d[0];var e=d[1]+Pa();c=d[2];var h=d[3];d=d[4];a.className="gac_f gac_p";var g=pb(b);e=$("http://"+g,e);a.innerHTML=['<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td><table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td style="line-height:117%;vertical-align:bottom"><a class=q ',e,">",c,'</a><td class="gac_e gac_d gac_i">Sponsored Link</table><tr><td class="gac_u gac_x gac_y" style="line-height:16px;padding-bottom:8px"><span class=gac_h',">",b,"</span>&nbsp; &nbsp;",h,d?" "+d:"","</table>"].join("")}},Lb={f:11,b:"b",C:f,g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];var e=d[2],h=d[3],g=d[4],i=d[5],s=d[6];d=d[7];var t=b.match(/^([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a class=q ',$(t,b),"><b>",c,"</b> - ",e," (",h,")</a><br><b>",g,"</b> <span class=gac_y><span class=gac_",i>=0?"h":"r",">",i," (",s,"%)</span> ",d,' - </span><a href=/help/stock_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a></span>'].join("")}},
Mb={f:12,b:"c",g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];d=d[2];for(var e="",h=d.length-1,g=0,i;g<h;g++){i=d[g];e+=[i[0],'<div class="gac_v">',i[1],"</div>"].join("")}i=d[h];e+=[i[0],"<br>",i[1]].join("");Rb(1,a,c,b,"www.flightstats.com",e)}},Nb={f:15,b:"d",e:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];a.innerHTML=["<b>",b,"</b> ",e," (",c,") in <b>",d,"</b>"].join("")}},Ob={f:13,b:"e",g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Rb(1,a,c,b,d)}},
Hb={f:14,b:"f",g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];Rb(1,a,c,b,d,e)}},Cb={f:0,b:"g",w:function(a){return a.j},e:function(a,b,c){var d=c[0];a.innerHTML=d;c.j=a.textContent;if(fa&&ya(b)=="p"){a.className="";a.innerHTML=["<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td class=gac_c>",
d,'<td class="gac_d gac_e fl"><a href=# onclick="return google.ac.dc(event,\'',b,"')\">Remove</a></table>"].join("");}}},Ib={f:19,b:"h",e:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,"</b>"].join("")}},Gb={f:17,b:"i",g:function(a,b){return b[3]},e:function(a,b,c,d){b=d[0];
c=d[1];var e=d[2];d=d[3];var h=d.match(/url=([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a ',$(h,d),">",b," &#151; ",c,": ",e,'</a><span class=gac_y style="line-height:16px"><br>According to <span class=gac_h>',h,"</span></span></span>"].join("")}},Pb={f:10,b:"j",e:function(a,b,c,d){b=d[0];c=d[1];var e=d[4];d=d[5];var h=function(g){var i=g[0],s=g[1],t=g[2],G=g[3];g=g[4];return['<td class=gac_w><img src="',i,'" alt="',s,'" title="',s,'"><td class="gac_c" style="line-height:112%;vertical-align:top">',
g,"<br>",t,"&deg; | ",G,"&deg;"].join("")};a.innerHTML=["<b>Weather:</b> ",e,"&deg;",c," in ",b,"<br><table class=gac_t><tr>",h(d[0]),h(d[1]),h(d[2]),h(d[3]),"</table>"].join("")}},Jb={f:20,b:"k",e:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,'</b> - <a href=/intl/en/help/currency_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a>'].join("")}},Kb={f:16,b:"l",w:function(a,b){return"define: "+b[0]},e:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Rb(1,a,
"Web definitions for <b>"+b+"</b>","/search?q=define:"+b.replace(" ","+"),"www.google.com",[c," - <span class=gac_i>",d,"</span>"].join(""))}},Eb={f:30,b:"m",e:function(a,b,c){a.innerHTML=["<span class=gac_z>Did you mean: </span>",wb(c[0])].join("")}},Fb={f:5,b:"n",w:function(a,b,c){return c},g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];d=d[1];a.className="gac_c gac_n";a.style.lineHeight="117%";var e=c[0];c=e.replace(/HTTPS?:\/\//gi,"");e=pb(e);/^HTTPS?:\/\//i.test(e)||(e=(b.indexOf("/url?url=https:")>
0?"https":"http")+"://"+e);b=$(e,b);a.innerHTML=["<span class=gac_x><a ",b,">",d,'</a><br><span class="gac_h gac_y"',">",c,"</span></span>"].join("");}};
function Rb(a,b,c,d,e,h,g){var i=d.indexOf("/url")?d:d.match(/url=([^&]*)/)[1];b.style.lineHeight="112%";b.innerHTML=["<a class=q ",$(i,d),">",c,'</a><span class="gac_y'+(a?" gac_x":"")+'">',h?h+"<br>":"",g?g+"<br>":"",e?"<span class=gac_h>"+e+"</span></span>":""].join("")}function Pa(){if(google.kEXPI)return"&expIds="+google.kEXPI;return""}l.c=rb;l.d=jb;l.dc=gb;l.h=kb;l.i=Ga;l.p=hb;l.r=qb;l.rd=Va;l.u=X;google.bind(window,"resize",Na);google.dstr&&google.dstr.push&&google.dstr.push(Da);})();
if(!window.gbar||!gbar.close){;};
(function(){var f=true,g=false;window.google.rt={};var h,i,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y;function aa(){h=30;i=[];l=k=g;m="";o=0;p=g;q=(new Date).getTime();r=100;s=0;t=g;y=[]}
google.rt.init=function(a,b,c){aa();if(n=document.getElementById(a)){if(c)if(c.maxResults)r=c.maxResults;document.onmousemove=function(){p=f};document.onkeydown=function(){p=f};b&&z(b);s+=n.getElementsByTagName("li").length;i.length==0&&window.setTimeout(A,3E3);ba(n,y);B(A,h);if(ca("sbu","sbd","sbb",a)){C.push(function(){l=f});D.push(function(){l=g});E(0,f)}da(ea,3E3,6E3)}};
google.rt.pause=function(){fa();F();var a=document.getElementById("rth");a=a.getElementsByTagName("span");G(a[0]);H(a[1]);x=(new Date).getTime()};google.rt.resume=function(){var a=((new Date).getTime()-x)/1E3;if(a>10)i=[];A();B(A,h);da(ea,2E3,6E3);a=document.getElementById("rth");a=a.getElementsByTagName("span");G(a[1]);H(a[0])};function G(a){a.style.display="none"}function H(a){a.style.display=""}
function B(a,b){var c=b;if(o){c=Math.pow(2,o)*5;c=(Math.random()+0.5)*c;c=Math.min(7200,c)}w=window.setTimeout(function(){a();B(a,b)},c*1E3)}function fa(){window.clearTimeout(w)}function da(a,b,c){u=window.setTimeout(function(){a();v=window.setInterval(a,c)},b)}function F(){window.clearTimeout(u);window.clearInterval(v)}
function ea(){if(!i.length||l){if(t){F();var a=document.getElementById("rth");a=a.getElementsByTagName("span");if(a.length>2){G(a[0]);G(a[1]);H(a[2])}}}else{var b=i.shift();a=b.e;var c=a.getElementsByTagName("li")[0];n.insertBefore(a,n.firstChild);b.updateDate();google.History.save(ga,{r:n.innerHTML,u:m,n:s,s:y,t:I()});var d=-google.getComputedStyle(c,"height")-google.getComputedStyle(c,"margin-bottom");b=n.scrollTop;if(b<20){E(b);a=[[a,"marginTop",d,0,google.fx.easeInAndOut]];google.fx.animate(1200,a)}else E(b-d)}}function z(a){if(a.results){var b=a.results.length;s+=b;b=b;for(var c;c=a.results[--b];)i.push(ha(c))}if(a.nextRequest)m=a.nextRequest;if(a.pollSeconds)h=a.pollSeconds}window.mbrt0={insert:function(a){a=eval("("+a+")");z(a)}};
function A(){if(p){p=g;q=(new Date).getTime()}else if((new Date).getTime()-q>24E4)return;t=s+5>r;if(!(k||t||!m)){var a=google.xhr();a.open("GET",m);a.onreadystatechange=function(){if(a.readyState==4){if(a.status==200){eval(a.responseText);o=0}else o++;k=g}};k=f;a.send(null)}}function ha(a){var b=document.createElement("div");b.innerHTML=a.html;return{e:b,updateDate:ia(b,y)}}var ga=google.History.client(function(a){n.innerHTML=a.r;m=a.u;s=a.n;y=a.s;ja(n,y,a.t);E(0,f);i=[];A()});
google.dstr.push(function(){F();fa()});var J,K,L,M,N,O,P,C,D,Q,R,S=g;function T(a){var b=google.getComputedStyle(a,"height");return b}function U(a){a=a.offsetTop;a-=M.offsetTop;return a}
function V(a){if(a)for(var b=0,c;c=C[b++];)c();else if(P)for(b=0;c=D[b++];)c();P=a}function W(a){var b=ka(a);if(b){var c=U(b);a||(c+=T(b)-R);la(c,f,300,function(){ma(a)})}}function la(a,b,c,d){var e=M.scrollHeight-R;e=e==0?0:na(a*(Q-Math.max(R/M.scrollHeight*Q,20))/e);e=[[L,"marginTop",google.getComputedStyle(L,"margin-top"),e,google.fx.easeInAndOut]];if(b)e.push([M,"scrollTop",M.scrollTop,a,google.fx.easeInAndOut,""]);else M.scrollTop=a;google.fx.animate(c,e,d)}
function ma(a){setTimeout(function(){P&&W(a)},200)}function ka(a){var b=M.childNodes;if(a)for(a=b.length-1;a>=0;--a){var c=b[a],d=U(c);if(c.nodeType==1&&d<M.scrollTop)return c}else for(a=0;c=b[a++];){d=U(c);if(c.nodeType==1&&d+T(c)>M.scrollTop+R)return c}}function X(a){var b=a.clientY-N;b=na(google.getComputedStyle(L,"margin-top")+b);L.style.marginTop=b+"px";M.scrollTop=b*(M.scrollHeight-R)/(Q-T(L));N=a.clientY}function na(a){return Math.max(0,Math.min(Q-T(L),a))}
function E(a,b){if(S){var c=T(L),d=Math.max(R/M.scrollHeight*Q,20),e=document.getElementById("sbbb");c=[[L,"height",c,d],[e,"marginTop",c-7,d-7]];if(!O){e=d=0;for(var j;j=M.childNodes[e++];)if(j.nodeType==1)d+=T(j);if(d>R){c.push([document.getElementById("sb"),"opacity",0,1,google.fx.linear,""]);O=f}}b=b?0:1200;la(a,g,b);google.fx.animate(b,c,function(){if(O)L.style.position="absolute"})}}
function Y(a,b){if(a.parentNode==L)a=L;b=70*(b?1:-1);oa(a,b);for(var c=0,d;d=a.childNodes[c++];)d.nodeType==1&&oa(d,b)}function oa(a,b){var c=a.style.backgroundPosition.match(/^-?\d+/),d=a.style.backgroundPosition.match(/\s+.*$/);a.style.backgroundPosition=parseInt(c,10)+b+"px "+(d?d:"")}
function ca(a,b,c,d){J=document.getElementById(a);K=document.getElementById(b);L=document.getElementById(c);M=document.getElementById(d);if(!(J&&K&&L&&M))return S=g;P=O=g;C=[];D=[];Q=google.getComputedStyle(document.getElementById("sbc"),"height")-1;R=google.getComputedStyle(M,"height");a=[J,K,L];for(b=0;c=a[b++];){google.bind(c,"mouseover",function(e){Y(e.target)});google.bind(c,"mouseout",function(e){Y(e.target,f)});c.onmousedown=function(){return g};
}google.bind(J,"mousedown",function(){V(f);W(f)});google.bind(K,"mousedown",function(){V(f);W()});google.bind(L,"mousedown",function(e){V(f);N=e.clientY;google.bind(document,"mousemove",X)});return S=f}
google.bind(document,"mouseup",function(){document.removeEventListener("mousemove",X,g);V(g)});google.dstr.push(function(){C=D=[];S=g});var pa=-1,Z;function qa(a,b){a=a.getElementsByTagName("div");for(var c=0,d;d=a[c++];)if(d.className=="rtdelta"){a=parseInt(d.innerHTML,10);return b-a}return g}
function I(){return Math.round((new Date).getTime()/1E3)}function ra(a,b){a=b-a;if(a<86400)if(a<45)return"seconds ago";else if(a<105)return"1 minute ago";else if(a<3345){a=Math.floor(a/60)+(a%60>=45?1:0);return"1 minutes ago".replace("1",a+"")}else if(a<6600)return"1 hour ago";else{a=Math.floor(a/3600)+(a%3600>=3E3?1:0);return"1 hours ago".replace("1",a+"")}return g}function sa(a,b,c,d){if(b)if(b=d(b,c))a.innerHTML=b}
function $(a){var b=[];a=a.getElementsByTagName("span");for(var c=0,d;d=a[c++];)d.className.match("rtd")&&b.push(d);return b}function ta(a){a=$(a);if(a.length>0)return a[0];return g}function ja(a,b,c){a=$(a);c=c||I();for(var d=0,e;e=a[d];d++)sa(e,b[d],c,Z)}function ia(a,b,c){var d=c||I();return function(){var e=ta(a);if(e){var j=qa(e,d);if(j){sa(e,j,I(),Z);b.unshift(j)}}}}
function ba(a,b,c){var d=$(a);c=c||I();for(var e=0,j;j=d[e++];)(j=qa(j,c))&&b.push(j);Z=ra;pa=window.setInterval(function(){ja(a,b)},6E4)}google.dstr.push(function(){window.clearInterval(pa)});})();
(function(){google.eggRequest=function(a){var b=document.createElement("SCRIPT");b.src="http://clients1.google.com/egg?ei="+google.kEI+"&cd="+a;google.append(b)};!google.neegg&&document.f&&document.f.btnI&&google.bind(document.f.btnI,"click",function(a){if(google.sn=="webhp"&&!google.neegg&&document.f.q.value==""){google.eggRequest("ifl");a.stopPropagation&&a.stopPropagation();a.cancelBubble=true;a.preventDefault&&a.preventDefault();return a.returnValue=false}});})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];
